export const siderList = [
  { id: 0, name: 'Buildings', route: 'buildings' },
  { id: 1, name: 'Apartments', route: 'apartments' },
  { id: 2, name: 'Residents', route: 'residents' },
  { id: 7, name: 'Visitors', route: 'visitors' },
  { id: 3, name: 'Security', route: 'security' },
  { id: 4, name: 'Notice Board', route: 'notice_board' },
  { id: 5, name: 'Complaints', route: 'complaints' },
  { id: 6, name: 'Bills', route: 'bills' },
];
export const months = [
  { id: 1, name: 'January'},
  { id: 2, name: 'February'},
  { id: 3, name: 'March'},
  { id: 4, name: 'April'},
  { id: 5, name: 'May'},
  { id: 6, name: 'June' },
  { id: 7, name: 'July' },
  { id: 8, name: 'August' },
  { id: 8, name: 'September' },
  { id: 8, name: 'October' },
  { id: 8, name: 'November' },
  { id: 8, name: 'December' },

];
export const apiURLs = {
buildings : "community/building/community_id/",
apartments : "community/apartment/community_id/",
apartmentsbyBuilding : "community/apartment/building_id/",
residents : "resident/resident/",
visitors : "resident/visitors/?community_id=",
noticeBoard : "noticeboard/notice_board/",
complaints : "complaint/complaints/",
updateComplaitStatus : "complaint/complaint/update_status/",
security : "administration/security/?community=",
searchUser : "user/users/verify/?phone_number=",
billing : "billing/bills_list/filter/community_id/",
billingbyBuilding : "billing/bills_list/filter/building_id/",
billingbyApartment : "billing/bills_list/filter/apartment_id/",
maintenanceFeeTypes : "administration/maintenance_fee_type/",
editMaintenanceFeeTypes : "administration/maintenance_fee_type_details/",
generateBills : "billing/generate_bills/",

addBuildings : "community/building/",
editBuildings : "community/building_details/",
addApartments : "community/apartment/",
editApartments : "community/apartment_details/",
addResidents : "resident/resident/",
editResidents : "resident/resident_details/",
addSecurity : "administration/security/",
}